### PR TITLE
fix: check recurring event with correct timezone

### PR DESCRIPTION
**Pull request by alexsmshchnko**
using local timezone leads to error in data comparison

### CODE REVIEW

**Comment by alexsmshchnko** [comment]
@apognu kindly approve

**Comment by apognu** [comment]
Sorry I missed this. Could you:

 * Give an example (in comment) of a wrong interpretation due to the bug?
 * Add a unit test that enforces your change so there is no regression on the future?

**Comment by morotsgurka** [comment]
I'll just add that i think I'm affected by this bug?

For example for this event:
```
BEGIN:VEVENT
RRULE:FREQ=WEEKLY;UNTIL=20241216T090000Z;INTERVAL=1;BYDAY=MO;WKST=MO
EXDATE;TZID=W. Europe Standard Time:20240909T100000,20240923T100000,2024100
 7T100000,20241021T100000,20241104T100000
UID:some-random-number
SUMMARY:Some event summary
DTSTART;TZID=W. Europe Standard Time:20240826T100000
DTEND;TZID=W. Europe Standard Time:20240826T110000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20241021T110643Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:Microsoft Teams-meeting\; Example room
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-ISRESPONSEREQUESTED:FALSE
END:VEVENT
```

The event is flagged as IsRecurring True, but ExcludeDates is empty

I had to add the timezone mapping to the parser since "W. Europe Standard Time" was not parsed by go and they returned as "UTC". 

```go
var tzMapping = map[string]string{
	"W. Europe Standard Time": "Europe/Stockholm",
}
gocal.SetTZMapper(func(s string) (*time.Location, error) {
	if tzid, ok := tzMapping[s]; ok {
		return time.LoadLocation(tzid)
	}
	return nil, fmt.Errorf("")
})
```

**Comment by alexsmshchnko** [comment]
```
BEGIN:VEVENT
DTSTART;TZID=Europe/Moscow:20240927T190000
DTEND;TZID=Europe/Moscow:20240927T200000
SUMMARY:Glutes and abs
UID:1a4pqkardx6cdkov4mj0
SEQUENCE:2
DTSTAMP:20241021T153542Z
CREATED:20240923T130134Z
DESCRIPTION:{\n\"name\": \"Glutes+abs\"\,\n\"announce_days\": 0\,\n\"announce_time\": \"09:20\"\,\n\"announce_close_days\": 0\,\n\"announce_close_time\": \"14:00\"\,\n\"trainer\": \"Galina\"\,\n}
URL:https://calendar.yandex.ru/event?event_id=2233769966
RRULE:FREQ=WEEKLY;BYDAY=FR;UNTIL=20241228T170000Z;INTERVAL=1
TRANSP:OPAQUE
CATEGORIES:studioYY
LAST-MODIFIED:20240923T130312Z
CLASS:PRIVATE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Moscow:20241025T190000
DTEND;TZID=Europe/Moscow:20241025T200000
SUMMARY:Glutes and abs
UID:1a4pqkardx6cdkov4mj0
SEQUENCE:1
DTSTAMP:20241021T153542Z
CREATED:20241018T073451Z
DESCRIPTION:{\n\"name\": \"Glutes+abs\"\,\n\"announce_days\": 0\,\n\"announce_time\": \"09:20\"\,\n\"announce_close_days\": 0\,\n\"announce_close_time\": \"14:00\"\,\n\"trainer\": \"Galina\"\,\n}
URL:https://calendar.yandex.ru/event?event_id=2263175119
RECURRENCE-ID;TZID=Europe/Moscow:20241025T190000
TRANSP:OPAQUE
CATEGORIES:studioYY
LAST-MODIFIED:20241018T073451Z
CLASS:PRIVATE
END:VEVENT
```
Param TZID is specified with timezone, but ignored in `parser.ParseTime` due to empty input `param`. So recurrence is used with UTC timezone.
It leads to inequality of dates when comparing `gocal.IsRecurringInstanceOverriden`

@apognu , should I add a test to the gocal_test.go file?

**Comment by apognu** [comment]
Thank you for explaining, it's clearer now.

Please add a test (a simple one will do, one event with a timezone-aware recurrence rule) and check that the repeated events happen at the right time.

Once that's done, I see no problem merging this in.

**Comment by alexsmshchnko** [comment]
@apognu , I added the test file. Please let me know if you have any questions.

**Comment by apognu** [comment]
LGTM.

**Comment by morotsgurka** [comment]
> LGTM.

Could you create a new release for this? Like v0.9.1 ?

**Comment by apognu** [comment]
Done. :+1:

**Comment by morotsgurka** [comment]
Just wanted to say that this seems to have fixed my issue, thanks!
I'm using this in a [current project](https://github.com/Teknikens-Hus/calendar-to-mqtt) to publish calendar events to MQTT topics (which will be parsed by ESP32 devices and displayed outside meeting rooms)

**Pull request merged**
